# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/IndentationConsistency:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
Layout/EmptyLines:
  Enabled: true
Layout/BlockAlignment:
  Enabled: true
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
