default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        update_computations:
          class: TriggerUpdateStatusJob
          args: []
          schedule: every 30 seconds
  workers:
    - queues: "*"
      threads: 5
      processes: 1
      polling_interval: 0.1

prod: &prod
  <<: *default

development:
 <<: *default

test:
 <<: *default

staging:
 <<: *prod

production:
 <<: *prod
