test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

plgrid_s3:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:s3, :access_key) %>
  secret_access_key: <%= Rails.application.credentials.dig(:s3, :secret_key) %>
  region: PL
  bucket: mltop-<%= Rails.env %>
  endpoint: https://s3p.cloud.cyfronet.pl
